export const gruposDisc = [
    ["Entusiasta", "Extrovertido(a)", "Popular", "Impulsivo(a)"],
    ["Rápido(a)", "Precavido(a)", "Reflexivo(a)", "Cuida los Detalles"],
    ["Lógico(a)", "Constante", "Tenaz", "Enérgico(a)"],
    ["Apacible", "Impaciente", "Calmado(a)", "Tranquilo(a)"],
    ["Cauteloso(a)", "Discreto(a)", "Analítico(a)", "Sociable"],
    ["Decidido(a)", "Complaciente", "Audaz", "Sistemático(a)"],
    ["Receptivo(a)", "Encantador(a)", "Leal", "Vigoroso(a)"],
    ["Bondadoso(a)", "Insistente", "Promotor(a)", "Tolerante"],
    ["Amigable", "Valeroso(a)", "Sociable", "Cautivador(a)"],
    ["Preciso(a)", "Anima a los demás", "Paciente", "Contento(a)"],
    ["Franco(a)", "Pacífico(a)", "Autosuficiente", "Exigente"],
    ["Tranquilo(a)", "Perfeccionista", "Certero(a)", "Apegado(a) a las normas"],
    ["Elocuente", "Reservado(a)", "Adaptable", "Le agrada discutir"],
    ["Controlado(a)", "Atento(a)", "Resuelto(a)", "Metódico(a)"],
    ["Tolerante", "Osado(a)", "Prevenido(a)", "Comedido(a)"],
    ["Decisivo(a)", "Alegre", "Vivaz", "Desenvuelto(a)"],
    ["Atrevido(a)", "Estimulante", "Agresivo(a)", "Jovial"],
    ["Concienzudo(a)", "Gentil", "Impetuoso(a)", "Preciso(a)"],
    ["Comunicativo(a)", "Perceptivo(a)", "Amistoso(a)", "Directo(a)"],
    ["Moderado(a)", "Independiente", "Discerniente", "Ecuánime"],
    ["Ameno(a)", "Competitivo(a)", "De trato Fácil", "Inquieto(a)"],
    ["Ingenioso(a)", "Considerado(a)", "Compasivo(a)", "Amable"],
    ["Investigador(a)", "Alegre", "Cauto(a)", "Elocuente"],
    ["Acepta Riesgos", "Sagaz", "Habla Directo", "Cuidadoso(a)"],
    ["Expresivo(a)", "Meticuloso(a)", "Evaluador(a)", "Prudente"],
    ["Cuidadoso(a)", "Obediente", "Generoso(a)", "Pionero(a)"],
    ["Dominante", "Ideas Firmes", "Animado(a)", "Espontáneo(a)"],
    ["Sensible", "Alentador(a)", "Persistente", "Colaborador"]
];
