// Cuestionario 16PF - Forma A (R. B. Cattell, adaptación TEA Ediciones).
// Cada ítem: [enunciado, [opción A, opción B, opción C]]
export const preguntas16pf = [
    ["He comprendido bien las instrucciones para contestar al Cuestionario:", ["Sí", "No estoy seguro", "No"]],
    ["Estoy dispuesto a contestar todas las cuestiones con sinceridad:", ["Sí", "No estoy seguro", "No"]],
    ["¿Cuáles de las siguientes palabras es diferente de las otras dos?:", ["Algo", "Nada", "Mucho"]],
    ["Poseo suficiente energía para enfrentarme a todos mis problemas:", ["Siempre", "Frecuentemente", "Raras veces"]],
    ["Evito criticar a la gente y sus ideas:", ["Sí", "Algunas veces", "No"]],
    ["Hago agudas y sarcásticas observaciones a la gente si creo que las merece:", ["Generalmente", "Algunas veces", "Nunca"]],
    ["Me gusta más la música semiclásica que las canciones populares:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Si veo peleándose a los niños de mis vecinos:", ["Les dejo solucionar sus problemas", "No estoy seguro", "Razono con ellos la solución"]],
    ["En situaciones sociales:", ["Fácilmente soy de los que toman iniciativas", "Intervengo algunas veces", "Prefiero quedarme tranquilamente a distancia"]],
    ["Sería más interesante ser:", ["Ingeniero de la construcción", "No estoy seguro entre los dos", "Escritor de teatro"]],
    ["Generalmente puedo tolerar a la gente presuntuosa, aunque fanfarronee o piense demasiado bien de ella misma:", ["Sí", "Término medio", "No"]],
    ["Cuando una persona no es honrada, casi siempre se le puede notar en la cara:", ["Verdadero", "Término medio", "Falso"]],
    ["Aceptaría mejor el riesgo de un trabajo donde pudiera tener ganancias mayores, aunque eventuales, que otro con sueldo pequeño, pero seguro:", ["Sí", "No estoy seguro", "No"]],
    ["De vez en cuando siento un vago temor o un repentino miedo, sin poder comprender las razones:", ["Sí", "Término medio", "No"]],
    ["Cuando me critican duramente por algo que no he hecho:", ["No me siento culpable", "Término medio", "Todavía me siento un poco culpable"]],
    ["Casi todo se puede comprar con dinero:", ["Sí", "No estoy seguro", "No"]],
    ["La mayoría de las personas serían más felices si convivieran más con la gente de su nivel e hicieran las cosas como los demás:", ["Sí", "Término medio", "No"]],
    ["En ocasiones, mirándome en un espejo, me entran dudas sobre lo que es mi derecha o izquierda:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Cuando algo realmente me pone furioso, suelo calmarme muy pronto:", ["Sí", "Término medio", "No"]],
    ["Preferiría tener una casa:", ["En un barrio con vida social", "Término medio", "Aislada en el bosque"]],
    ["Con el mismo horario y sueldo, sería más interesante ser:", ["El cocinero de un buen restaurante", "No estoy seguro entre ambos", "El que sirve las mesas en el restaurante"]],
    ["«Cansado» es a «trabajar» como «orgulloso» es a:", ["Sonreír", "Tener éxito", "Ser feliz"]],
    ["Me pongo algo nervioso ante animales salvajes, incluso cuando están encerrados en fuertes jaulas:", ["Sí", "No estoy seguro", "No"]],
    ["Una ley anticuada debería cambiarse:", ["Sólo después de muchas discusiones", "Término medio", "Inmediatamente"]],
    ["La mayor parte de las personas me consideran un interlocutor agradable:", ["Sí", "No estoy seguro", "No"]],
    ["Me gusta salir a divertirme o ir a un espectáculo:", ["Más de una vez por semana (más de lo corriente)", "Alrededor de una vez por semana (lo corriente)", "Menos de una vez por semana (menos de lo corriente)"]],
    ["Cuando veo gente desaliñada y sucia:", ["Lo acepto simplemente", "Término medio", "Me disgusta y me fastidia"]],
    ["Estando en un grupo social me siento un poco turbado si de pronto paso a ser el foco de atención:", ["Sí", "Término medio", "No"]],
    ["Cuando voy por la calle prefiero detenerme antes a ver a un artista pintando que a escuchar a la gente discutir:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Cuando me ponen al frente de algo, insisto en que se sigan mis instrucciones; en caso contrario, renuncio:", ["Sí", "Algunas veces", "No"]],
    ["Sería mejor que las vacaciones fueran más largas y obligatorias para todas las personas:", ["De acuerdo", "No estoy seguro", "En desacuerdo"]],
    ["Hablo acerca de mis sentimientos:", ["Sólo si es necesario", "Término medio", "Fácilmente, siempre que tengo ocasión"]],
    ["Me siento muy abatido cuando la gente me critica en un grupo:", ["Verdadero", "Término medio", "Falso"]],
    ["Si mi jefe (profesor) me llama a su despacho:", ["Aprovecho la ocasión para pedirle algo que deseo", "Término medio", "Temo haber hecho algo malo"]],
    ["Mis decisiones se apoyan más en:", ["El corazón", "Los sentimientos y la razón por igual", "La cabeza"]],
    ["En mi adolescencia pertenecía a equipos deportivos:", ["Algunas veces", "A menudo", "La mayoría de las veces"]],
    ["Cuando hablo con alguien, me gusta:", ["Decir las cosas tal como se me ocurren", "Término medio", "Organizar antes mis ideas"]],
    ["A veces me pongo en estado de tensión y agitación cuando pienso en los sucesos del día:", ["Sí", "Término medio", "No"]],
    ["He sido elegido para hacer algo:", ["Sólo en pocas ocasiones", "Varias veces", "Muchas veces"]],
    ["¿Cuál de las siguientes cosas es diferente de las otras dos?:", ["Vela", "Luna", "Luz eléctrica"]],
    ["«Sorpresa» es a «extraño» como «miedo» es a:", ["Valeroso", "Ansioso", "Terrible"]],
    ["A veces no puedo dormirme porque tengo una idea que me da vueltas en la cabeza:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Me siento desasosegado cuando trabajo en un proyecto que requiere una acción rápida que afecta a los demás:", ["Verdadero", "Término medio", "Falso"]],
    ["Indudablemente tengo menos amigos que la mayoría de las personas:", ["Sí", "Término medio", "No"]],
    ["Aborrecería tener que estar en un lugar donde hubiera poca gente con quien hablar:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Creo que es más importante mucha libertad que buena educación y respeto a la ley:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Siempre me alegra formar parte de un grupo grande, como una reunión, un baile o una asamblea:", ["Sí", "Término medio", "No"]],
    ["En mi época de estudiante me gustaba (me gusta):", ["La música", "No estoy seguro", "La actividad de tipo manual"]],
    ["Si alguien se enfada conmigo:", ["Intento calmarle", "No estoy seguro", "Me irrito con él"]],
    ["Para los padres es más importante:", ["Ayudar a sus hijos a desarrollarse afectivamente", "Término medio", "Enseñarles a controlar sus emociones"]],
    ["Siento de vez en cuando la necesidad de ocuparme en una actividad física enérgica:", ["Sí", "Término medio", "No"]],
    ["Hay veces en que no me siento con humor para ver a alguien:", ["Muy raramente", "Término medio", "Muy a menudo"]],
    ["A veces los demás me advierten que yo muestro mi excitación demasiado claramente en la voz y en los modales:", ["Sí", "Término medio", "No"]],
    ["Lo que el mundo necesita es:", ["Ciudadanos más sensatos y constantes", "No estoy seguro", "Más «idealistas» con proyectos para un mundo mejor"]],
    ["Preferiría tener un negocio propio, no compartido con otra persona:", ["Sí", "No estoy seguro", "No"]],
    ["Tengo mi habitación organizada de un modo inteligente y estético, con las cosas colocadas casi siempre en lugares conocidos:", ["Sí", "Término medio", "No"]],
    ["En ocasiones dudo si la gente con quien estoy hablando se interesa realmente por lo que digo:", ["Sí", "Término medio", "No"]],
    ["Si tuviera que escoger, preferiría ser:", ["Guarda forestal", "No estoy seguro", "Profesor de Enseñanza Media"]],
    ["¿Cuál de las siguientes fracciones es diferente de las otras dos?:", ["3/7", "3/9", "3/11"]],
    ["«Tamaño» es a «longitud» como «delito» es a:", ["Prisión", "Castigo", "Robo"]],
    ["En mi vida personal consigo casi siempre todos mis propósitos:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Tengo algunas características en las que me siento claramente superior a la mayor parte de la gente:", ["Sí", "No estoy seguro", "No"]],
    ["Sólo asisto a actos sociales cuando estoy obligado, y me mantengo aparte en las demás ocasiones:", ["Sí", "No estoy seguro", "No"]],
    ["Es mejor ser cauto y esperar poco que optimista y esperar siempre el éxito:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Algunas veces la gente dice que soy descuidado, aunque me considera una persona agradable:", ["Sí", "Término medio", "No"]],
    ["Suelo permanecer callado delante de personas mayores (con mucha más experiencia, edad o jerarquía):", ["Sí", "Término medio", "No"]],
    ["Tengo un buen sentido de la orientación (sitúo fácilmente los puntos cardinales), cuando me encuentro en un lugar desconocido:", ["Sí", "Término medio", "No"]],
    ["Cuando leo en una revista un artículo tendencioso o injusto, me inclino más a olvidarlo que a replicar o «devolver el golpe»:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["En tareas de grupo, preferiría:", ["Intentar mejorar los preparativos", "Término medio", "Llevar las actas o registros y procurar que se cumplan las normas"]],
    ["Me gustaría más andar con personas corteses que con individuos rebeldes y toscos:", ["Sí", "Término medio", "No"]],
    ["Si mis conocidos me tratan mal o muestran que yo les disgusto:", ["No me importa nada", "Término medio", "Me siento abatido"]],
    ["Siempre estoy alerta ante los intentos de propaganda en las cosas que leo:", ["Sí", "No estoy seguro", "No"]],
    ["Me gustaría más gozar de la vida tranquilamente y a mi modo que ser admirado por mis resultados:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Para estar informado, prefiero:", ["Discutir los acontecimientos con la gente", "Término medio", "Apoyarme en las informaciones periodísticas de actualidad"]],
    ["Me encuentro formado (maduro) para la mayor parte de las cosas:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Me encuentro más abatido que ayudado por el tipo de crítica que la gente suele hacer:", ["A menudo", "Ocasionalmente", "Nunca"]],
    ["En las fiestas de cumpleaños:", ["Me gusta hacer regalos personales", "No estoy seguro", "Pienso que comprar regalos es un poco latoso"]],
    ["«AB» es a «dc» como «SR» es:", ["qp", "pq", "tu"]],
    ["«Mejor» es a «pésimo» como «menor» es a:", ["Mayor", "Óptimo", "Máximo"]],
    ["Mis amigos me han fallado:", ["Muy rara vez", "Ocasionalmente", "Muchas veces"]],
    ["Cuando me siento abatido hago grandes esfuerzos por ocultar mis sentimientos a los demás:", ["Verdadero", "Término medio", "Falso"]],
    ["Gasto gran parte de mi tiempo libre hablando con los amigos sobre situaciones sociales agradables vividas en el pasado:", ["Sí", "Término medio", "No"]],
    ["Pensando en las dificultades de mi trabajo:", ["Intento organizarme antes de que aparezcan", "Término medio", "Doy por supuesto que puedo dominarlas cuando vengan"]],
    ["Me cuesta bastante hablar o dirigir la palabra a un grupo numeroso:", ["Sí", "Término medio", "No"]],
    ["He experimentado en varias situaciones sociales el llamado «nerviosismo del orador»:", ["Muy frecuentemente", "Ocasionalmente", "Casi nunca"]],
    ["Prefiero leer:", ["Una narración realista de contiendas militares o políticas", "No estoy seguro", "Una novela imaginativa y delicada"]],
    ["Cuando la gente autoritaria trata de dominarme, hago justamente lo contrario de lo que quiere:", ["Sí", "Término medio", "No"]],
    ["Suelo olvidar muchas cosas triviales y sin importancia, tales como los nombres de las calles y tiendas de la ciudad:", ["Sí", "Término medio", "No"]],
    ["Me gustaría la profesión de veterinario, ocupado con las enfermedades y curación de los animales:", ["Sí", "Término medio", "No"]],
    ["Me resulta embarazoso que me dediquen elogios o cumplidos:", ["Sí", "Término medio", "No"]],
    ["Siendo adolescente, cuando mi opinión era distinta de la de mis padres, normalmente:", ["Mantenía mi opinión", "Término medio", "Aceptaba su autoridad"]],
    ["Me gusta tomar parte activa en las tareas sociales, trabajos de comité, etc.:", ["Sí", "Término medio", "No"]],
    ["Al llevar a cabo una tarea, no estoy satisfecho hasta que se ha considerado con toda atención el menor detalle:", ["Verdadero", "Término medio", "Falso"]],
    ["Tengo ocasiones en que me es difícil alejar un sentimiento de compasión hacia mí mismo:", ["A menudo", "Algunas veces", "Nunca"]],
    ["Siempre soy capaz de controlar perfectamente la expresión de mis sentimientos:", ["Sí", "Término medio", "No"]],
    ["Ante un nuevo invento utilitario, me gustaría:", ["Trabajar sobre él en el laboratorio", "No estoy seguro", "Venderlo a la gente"]],
    ["La siguiente serie de letras XOOOOXXOOOXXX continúa con el grupo:", ["OXXX", "OOXX", "XOOO"]],
    ["Algunas personas parecen ignorarme o evitarme, aunque no sé por qué:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["La gente me trata menos razonablemente de lo que merecen mis buenas intenciones:", ["A menudo", "Ocasionalmente", "Nunca"]],
    ["Aunque no sea en un grupo mixto de mujeres y hombres, me disgusta que se use un lenguaje obsceno:", ["Sí", "Término medio", "No"]],
    ["Me gusta hacer cosas atrevidas y temerarias sólo por el placer de divertirme:", ["Sí", "Término medio", "No"]],
    ["Me resulta molesta la vista de una habitación muy sucia:", ["Sí", "Término medio", "No"]],
    ["Cuando estoy en un grupo pequeño, me agrada quedarme en un segundo término y dejar que otros lleven el peso de la conversación:", ["Sí", "Término medio", "No"]],
    ["Me resulta fácil mezclarme con la gente en una reunión social:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Sería más interesante ser:", ["Orientador vocacional para ayudar a los jóvenes en la búsqueda de su profesión", "No estoy seguro", "Directivo de una empresa industrial"]],
    ["Por regla general, mis jefes y mi familia me encuentran defectos sólo cuando realmente existen:", ["Verdadero", "Término medio", "Falso"]],
    ["Me disgusta el modo con que algunas personas se fijan en otras en la calle o en las tiendas:", ["Sí", "Término medio", "No"]],
    ["Como los alimentos con gusto y placer, aunque no siempre tan cuidadosa y educadamente como otras personas:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Temo algún castigo incluso cuando no he hecho nada malo:", ["A menudo", "Ocasionalmente", "Nunca"]],
    ["Me gustaría más tener un trabajo con:", ["Un determinado sueldo fijo", "Término medio", "Un sueldo más alto pero siempre que demuestre a los demás que lo merezco"]],
    ["Me molesta que la gente piense que mi comportamiento es demasiado raro o fuera de lo corriente:", ["Mucho", "Algo", "Nada en absoluto"]],
    ["A veces dejo que sentimientos de envidia o celos influyan en mis acciones:", ["Sí", "Término medio", "No"]],
    ["En ocasiones, contrariedades muy pequeñas me irritan mucho:", ["Sí", "Término medio", "No"]],
    ["Siempre duermo bien, nunca hablo en sueños ni me levanto sonámbulo:", ["Sí", "Término medio", "No"]],
    ["Me resultaría más interesante trabajar en una empresa:", ["Atendiendo a los clientes", "Término medio", "Llevando las cuentas o los archivos"]],
    ["«Azada» es a «cavar» como «cuchillo» es a:", ["Cortar", "Afilar", "Picar"]],
    ["Cuando la gente no es razonable, yo normalmente:", ["Me quedo tan tranquilo", "Término medio", "La menosprecio"]],
    ["Si los demás hablan en voz alta cuando estoy escuchando música:", ["Puedo concentrarme en ella sin que me molesten", "Término medio", "Eso me impide disfrutar de ella y me incomoda"]],
    ["Creo que se me describe mejor como:", ["Comedido y reposado", "Término medio", "Enérgico"]],
    ["Preferiría vestirme con sencillez y corrección que con un estilo personal y llamativo:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Me niego a admitir sugerencias bien intencionadas de los demás, aunque sé que no debería hacerlo:", ["Algunas veces", "Casi nunca", "Nunca"]],
    ["Cuando es necesario que alguien emplee un poco de diplomacia y persuasión para conseguir que la gente actúe, generalmente sólo me lo encargan a mí:", ["Sí", "Término medio", "No"]],
    ["Me considero a mí mismo como una persona muy abierta y sociable:", ["Sí", "Término medio", "No"]],
    ["Me gusta la música:", ["Ligera, movida y animada", "Término medio", "Emotiva y sentimental"]],
    ["Si estoy completamente seguro de que una persona es injusta o se comporta egoístamente, se lo digo, incluso si esto me causa problemas:", ["Sí", "Término medio", "No"]],
    ["En un viaje largo, preferiría:", ["Leer algo profundo pero interesante", "No estoy seguro", "Pasar el tiempo charlando sobre cualquier cosa con un compañero de viaje"]],
    ["En una situación que puede llegar a ser peligrosa, creo que es mejor alborotar o hablar alto, aún cuando se pierdan la calma y la cortesía:", ["Sí", "Término medio", "No"]],
    ["Es muy exagerada la idea de que la enfermedad proviene tanto de causas mentales como físicas:", ["Sí", "Término medio", "No"]],
    ["En cualquier gran ceremonia oficial debería mantenerse la pompa y el esplendor:", ["Sí", "Término medio", "No"]],
    ["Cuando hay que hacer algo, me gustaría más trabajar:", ["En equipo", "No estoy seguro", "Yo solo"]],
    ["Creo firmemente que «tal vez el jefe no tenga siempre la razón, pero siempre tiene la razón por ser el jefe»:", ["Sí", "No estoy seguro", "No"]],
    ["Suelo enfadarme con las personas demasiado pronto:", ["Sí", "Término medio", "No"]],
    ["Siempre puedo cambiar viejos hábitos sin dificultad y sin volver a ellos:", ["Sí", "Término medio", "No"]],
    ["Si el sueldo fuera el mismo, preferiría ser:", ["Abogado", "No estoy seguro entre ambos", "Navegante o piloto"]],
    ["«Llama» es a «calor» como «rosa» es a:", ["Espina", "Pétalo", "Aroma"]],
    ["Cuando se acerca el momento de algo que he planeado y he esperado, en ocasiones pierdo la ilusión por ello:", ["Verdadero", "Término medio", "Falso"]],
    ["Puedo trabajar cuidadosamente en la mayor parte de las cosas sin que me molesten las personas que hacen mucho ruido a mi alrededor:", ["Sí", "Término medio", "No"]],
    ["En ocasiones hablo a desconocidos sobre cosas que considero importantes, aunque no me pregunten sobre ellas:", ["Sí", "Término medio", "No"]],
    ["Me atrae más pasar una tarde ocupado en una tarea tranquila a la que tenga afición que estar en una reunión animada:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Cuando debo decidir algo, tengo siempre presentes las reglas básicas de lo justo y lo injusto:", ["Sí", "Término medio", "No"]],
    ["En el trato social:", ["Muestro mis emociones tal como las siento", "Término medio", "Guardo mis emociones para mis adentros"]],
    ["Admiro más la belleza de un poema que la de un arma de fuego bien construida:", ["Sí", "No estoy seguro", "No"]],
    ["A veces digo en broma disparates, sólo para sorprender a la gente y ver qué responden:", ["Sí", "Término medio", "No"]],
    ["Me agradaría ser un periodista que escribiera sobre teatro, conciertos, ópera, etc.:", ["Sí", "No estoy seguro", "No"]],
    ["Nunca siento la necesidad de garabatear, dibujar o moverme cuando estoy sentado en una reunión:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Si alguien me dice algo que yo sé que no es cierto, suelo pensar:", ["«Es un mentiroso»", "Término medio", "«Evidentemente no está bien informado»"]],
    ["La gente me considera con justicia una persona activa pero con éxito sólo mediano:", ["Sí", "No estoy seguro", "No"]],
    ["Si se suscitara una controversia violenta entre otros miembros de un grupo de discusión:", ["Me gustaría ver quién es el «ganador»", "Término medio", "Desearía que se suavizara de nuevo la situación"]],
    ["Me gusta planear mis cosas solo, sin interrupciones y sugerencias de otros:", ["Sí", "Término medio", "No"]],
    ["Me gusta seguir mis propios caminos, en vez de actuar según normas establecidas:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Me pongo nervioso (tenso) cuando pienso en todas las cosas que tengo que hacer:", ["Sí", "Algunas veces", "No"]],
    ["No me perturba que la gente me haga alguna sugerencia cuando estoy jugando:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Me parece más interesante ser:", ["Artista", "No estoy seguro", "Secretario de un club social"]],
    ["¿Cuál de las siguientes palabras es diferente de las otras dos?:", ["Ancho", "Zigzag", "Recto"]],
    ["He tenido sueños tan intensos que no me han dejado dormir bien:", ["A menudo", "Ocasionalmente", "Prácticamente nunca"]],
    ["Aunque tenga pocas posibilidades de éxito, creo que todavía me merece la pena correr el riesgo:", ["Sí", "Término medio", "No"]],
    ["Cuando yo sé muy bien lo que el grupo tiene que hacer, me gusta ser el único en dar las órdenes:", ["Sí", "Término medio", "No"]],
    ["Me consideran una persona muy entusiasta:", ["Sí", "Término medio", "No"]],
    ["Soy una persona bastante estricta, e insisto siempre en hacer las cosas tan correctamente como sea posible:", ["Verdadero", "Término medio", "Falso"]],
    ["Me disgusta un poco que la gente me esté mirando cuando trabajo:", ["Sí", "Término medio", "No"]],
    ["Como no siempre es posible conseguir las cosas utilizando gradualmente métodos razonables, a veces es necesario emplear la fuerza:", ["Verdadero", "Término medio", "Falso"]],
    ["Si se pasa por alto una buena observación mía:", ["La dejo pasar", "Término medio", "Doy a la gente la oportunidad de volver a escucharla"]],
    ["Me gustaría hacer el trabajo de un oficial encargado de los casos de delincuentes bajo fianza:", ["Sí", "Término medio", "No"]],
    ["Hay que ser prudente antes de mezclarse con cualquier desconocido, puesto que hay peligros de infección y de otro tipo:", ["Sí", "No estoy seguro", "No"]],
    ["En un viaje al extranjero, preferiría ir en un grupo organizado, con un experto, que planear yo mismo los lugares que deseo visitar:", ["Sí", "No estoy seguro", "No"]],
    ["Si la gente se aprovecha de mi amistad, no me quedo resentido y lo olvido pronto:", ["Verdadero", "Término medio", "Falso"]],
    ["Creo que la sociedad debería aceptar nuevas costumbres, de acuerdo con la razón, y olvidar los viejos usos y tradiciones:", ["Sí", "Término medio", "No"]],
    ["Aprendo mejor:", ["Leyendo un libro bien escrito", "Término medio", "Participando en un grupo de discusión"]],
    ["Me gusta esperar a estar seguro de que lo que voy a decir es correcto, antes de exponer mis ideas:", ["Siempre", "Generalmente", "Sólo si es posible"]],
    ["Algunas veces me «sacan de quicio» de un modo insoportable pequeñas cosas, aunque reconozca que son triviales:", ["Sí", "Término medio", "No"]],
    ["No suelo decir, sin pensarlas, cosas que luego lamento mucho:", ["Verdadero", "No estoy seguro", "Falso"]],
    ["Si se me pidiera colaborar en una campaña caritativa:", ["Aceptaría", "No estoy seguro", "Diría cortésmente que estoy muy ocupado"]],
    ["«Pronto» es a «nunca» como «cerca» es a:", ["En ningún sitio", "Lejos", "En otro sitio"]],
    ["Si cometo una falta social desagradable, puedo olvidarla pronto:", ["Sí", "No estoy seguro", "No"]],
    ["Se me considera un «hombre de ideas» que casi siempre puede apuntar alguna solución a un problema:", ["Sí", "Término medio", "No"]],
    ["Creo que se me da mejor mostrar:", ["Aplomo en las pugnas y discusiones de una reunión", "No estoy seguro", "Tolerancia con los deseos de los demás"]],
    ["Me gusta un trabajo que presente cambios, variedad y viajes, aunque implique algún peligro:", ["Sí", "Término medio", "No"]],
    ["Me gusta un trabajo que requiera dotes de atención y exactitud:", ["Sí", "Término medio", "No"]],
    ["Soy de ese tipo de personas con tanta energía que siempre están ocupadas:", ["Sí", "No estoy seguro", "No"]],
    ["En mi época de estudiante prefería (prefiero):", ["Lengua o Literatura", "No estoy seguro", "Matemáticas o Aritmética"]],
    ["Algunas veces me ha turbado el que la gente diga a mi espalda cosas desagradables de mí sin fundamento:", ["Sí", "No estoy seguro", "No"]],
    ["Hablar con personas corrientes, convencionales y rutinarias:", ["Es a menudo muy interesante e instructivo", "Término medio", "Me fastidia porque no hay profundidad o se trata de chismes y cosas sin importancia"]],
    ["Algunas cosas me irritan tanto que creo que entonces lo mejor es no hablar:", ["Sí", "Término medio", "No"]],
    ["En la formación del niño, es más importante:", ["Darle bastante afecto", "Término medio", "Procurar que aprenda hábitos y actitudes deseables"]],
    ["Los demás me consideran una persona firme e imperturbable, impasible ante los vaivenes de las circunstancias:", ["Sí", "Término medio", "No"]],
    ["Creo que en el mundo actual es más importante resolver:", ["El problema de la intención moral", "No estoy seguro", "Los problemas políticos"]],
    ["Creo que no me he saltado ninguna cuestión y he contestado a todas de modo apropiado:", ["Sí", "No estoy seguro", "No"]]
];

export const instrucciones16pf = [
    "A continuación encontrará una serie de cuestiones que permitirán conocer sus actitudes e intereses. En general, no existen contestaciones correctas o incorrectas, porque las personas tienen distintos intereses y ven las cosas desde distintos puntos de vista. Conteste con sinceridad; de esta forma se podrá conocer mejor su forma de ser.",
    "Cada cuestión tiene tres posibles respuestas (A, B o C). Lea atentamente cada cuestión y las tres posibles respuestas.",
    "No piense demasiado las cuestiones ni emplee mucho tiempo en decidirse. Conteste pensando en lo que es habitual para usted.",
    "Evite señalar la respuesta «término medio» o equivalente, excepto cuando le sea imposible decidirse por las otras.",
    "Procure no dejar ninguna cuestión sin contestar, aunque alguna no se aplique perfectamente a su caso.",
    "Conteste sinceramente. No señale sus respuestas pensando en lo que «es bueno» o «lo que interesa» para impresionar al examinador."
];
